name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP (GoDaddy)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: ./*
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}/
          sftp_only: true
          # optional, but helps prevent partial uploads
          delete_remote_files: false
          exclude: |
            .git*
            .github/**
            node_modules/**
            composer.lock
            package-lock.json
            .DS_Store
