name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build marker
        run: |
          echo "Build: $(date +%F-%T)" > build.txt
          echo "Commit: $GITHUB_SHA" >> build.txt
          echo "Deployed from GitHub Actions" >> build.txt

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP using lftp
        env:
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -u client_2f8ef049a7_440246,"$SFTP_PASSWORD" sftp://u0p.327.myftpupload.com:22 <<'LFTP_COMMANDS'
          set sftp:auto-confirm yes
          set ssl:verify-certificate no

          echo "=== Listing root directory ==="
          ls -la

          echo "=== Trying to find WordPress installation ==="
          !echo "Attempting: wp-content"
          cd wp-content || !echo "FAILED: wp-content not found"

          !echo "Attempting: html"
          cd html || !echo "Still in root, trying html"

          !echo "Current directory after navigation:"
          pwd
          ls -la

          echo "=== Looking for plugins directory ==="
          cd plugins || mkdir plugins
          pwd
          ls -la

          echo "=== Creating/entering plugin directory ==="
          mkdir -p submittal-spec-sheet-builder
          cd submittal-spec-sheet-builder
          pwd

          echo "=== Uploading files ==="
          mirror --reverse --verbose --only-newer --exclude .git/ --exclude .github/ --exclude node_modules/ $GITHUB_WORKSPACE ./

          echo "=== Verifying upload - listing deployed files ==="
          ls -la
          !echo "Checking for key files:"
          ls -la build.txt readme.txt submittal-form-builder.php

          bye
          LFTP_COMMANDS
