name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build marker
        run: |
          echo "Build: $(date +%F-%T)" > build.txt
          echo "Commit: $GITHUB_SHA" >> build.txt
          echo "Deployed from GitHub Actions" >> build.txt

      - name: Deploy via SFTP (GoDaddy Managed WordPress)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: u0p.327.myftpupload.com
          username: client_2f8ef049a7_440246
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "./*"
          target: "/wp-content/plugins/submittal-spec-sheet-builder/"
          strip_components: 0
          overwrite: true
          rm: false
