name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build marker
        run: |
          echo "Build: $(date +%F-%T)" > build.txt
          echo "Commit: $GITHUB_SHA" >> build.txt
          echo "Deployed from GitHub Actions" >> build.txt

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP using lftp
        env:
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -u client_2f8ef049a7_440246,"$SFTP_PASSWORD" sftp://u0p.327.myftpupload.com:22 <<EOF
          set sftp:auto-confirm yes
          set ssl:verify-certificate no

          echo "=== Listing root directory ==="
          ls -la

          echo "=== Checking for wp-content ==="
          cd wp-content 2>/dev/null || cd html/wp-content 2>/dev/null || cd public_html/wp-content 2>/dev/null || cd www/wp-content 2>/dev/null
          pwd
          ls -la

          echo "=== Creating plugin directory ==="
          cd plugins
          mkdir -p submittal-spec-sheet-builder

          echo "=== Deploying files ==="
          cd submittal-spec-sheet-builder
          lcd $GITHUB_WORKSPACE
          mirror --reverse --verbose --exclude .git/ --exclude .github/ --exclude node_modules/ ./ ./

          bye
          EOF
