name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp (for SFTP mirror)
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy plugin via SFTP mirror (try common Managed WP paths)
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          set -e
          echo "Creating build marker..."
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') $GITHUB_SHA" > build.txt

          deploy_one () {
            REMOTE_DIR="$1"
            echo "::group::Deploying to sftp://${SFTP_HOST}${REMOTE_DIR}"
            lftp -u "${SFTP_USERNAME},${SFTP_PASSWORD}" sftp://${SFTP_HOST} -e "
              set sftp:auto-confirm yes;
              set net:max-retries 1;
              set net:reconnect-interval-base 5;
              set net:timeout 20;
              mkdir -p ${REMOTE_DIR};
              mirror -R \
                --verbose \
                --only-newer \
                --parallel=2 \
                --exclude-glob .git* \
                --exclude-glob .github/ \
                --exclude-glob node_modules/ \
                ./ ${REMOTE_DIR};
              bye;
            "
            echo "::endgroup::"
          }

          # Try all plausible plugin paths on GoDaddy Managed WP
          deploy_one "/wp-content/plugins/submittal-spec-sheet-builder"
          deploy_one "/html/wp-content/plugins/submittal-spec-sheet-builder"
          deploy_one "/public_html/wp-content/plugins/submittal-spec-sheet-builder"

      - name: Verify deployed files via HTTP
        run: |
          set -e
          URL="https://u0p.327.myftpupload.com/wp-content/plugins/submittal-spec-sheet-builder/build.txt"
          echo "Checking $URL ..."
          code=$(curl -s -o /tmp/build.txt -w "%{http_code}" "$URL" || true)
          echo "HTTP $code"
          if [ "$code" != "200" ]; then
            echo "build.txt not found at expected URL — deploy may have landed under /html or /public_html."
            exit 1
          fi
          echo "---- build.txt ----"
          cat /tmp/build.txt
