name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP (GoDaddy)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: client_2f8ef049a7_440246     # ← hardcoded temporarily
          password: ${{ secrets.SFTP_PASSWORD }} # still from secret
          port: 22
          sftp_only: true
          local_path: ./*
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}/
          delete_remote_files: false
