name: Deploy to GoDaddy SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-plugin
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build marker
        run: |
          echo "Build: $(date +%F-%T)" > build.txt
          echo "Commit: $GITHUB_SHA" >> build.txt
          echo "Deployed from GitHub Actions" >> build.txt

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Explore SFTP directory structure
        env:
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        run: |
          lftp -u client_2f8ef049a7_440246,"$SFTP_PASSWORD" sftp://u0p.327.myftpupload.com:22 <<'EXPLORE'
          set sftp:auto-confirm yes
          set ssl:verify-certificate no

          echo "=== ROOT DIRECTORY ==="
          pwd
          ls -la

          echo ""
          echo "=== SEARCHING FOR WORDPRESS ==="

          echo "Trying: ./html"
          cd html 2>/dev/null && pwd && ls -la || echo "Not found"
          cd .. 2>/dev/null

          echo ""
          echo "Trying: ./www"
          cd www 2>/dev/null && pwd && ls -la || echo "Not found"
          cd .. 2>/dev/null

          echo ""
          echo "Trying: ./public_html"
          cd public_html 2>/dev/null && pwd && ls -la || echo "Not found"
          cd .. 2>/dev/null

          echo ""
          echo "Trying: ./httpdocs"
          cd httpdocs 2>/dev/null && pwd && ls -la || echo "Not found"
          cd .. 2>/dev/null

          echo ""
          echo "=== SEARCHING FOR EXISTING PLUGIN ==="
          find . -maxdepth 5 -type d -name "submittal-spec-sheet-builder" 2>/dev/null || echo "Plugin directory not found"

          echo ""
          echo "=== SEARCHING FOR wp-config.php ==="
          find . -maxdepth 3 -name "wp-config.php" 2>/dev/null || echo "wp-config.php not found"

          bye
          EXPLORE
